//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InTouch_WEBClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passed_tests
    {
        public System.Guid Id { get; set; }
        public System.Guid Test_ID { get; set; }
        public System.Guid Question_ID { get; set; }
        public System.Guid User_ID { get; set; }
        public System.Guid Selected_answer_ID { get; set; }
    
        public virtual Question_options Question_options { get; set; }
        public virtual Questions Questions { get; set; }
        public virtual Users Users { get; set; }
        public virtual Tests Tests { get; set; }
    }
}
