//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InTouch_WEBClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignalRConnections
    {
        public System.Guid Connection_ID { get; set; }
        public System.Guid User_Agent { get; set; }
        public bool Connected { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
