//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InTouch_WEBClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tests_additions
    {
        public System.Guid Id { get; set; }
        public string Object { get; set; }
        public string Value { get; set; }
    }
}
